# Generated by Django 4.2.8 on 2023-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='comment1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='comment2',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='decorator1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='decorator2',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='texture1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='texture2',
        ),
        migrations.AlterField(
            model_name='furniture',
            name='material',
            field=models.CharField(max_length=50, verbose_name='Наиминование'),
        ),
    ]
